### ISSUE TITLE
테스트용 서버 추가 구축

### ISSUE THREAD

**Issue by myway00** [ECI-Equipment-module/eci-backend#24]
### TODO 

1) 서버 DB 테스트용 (3000) / NETLIFY (naughty-ramen) 용 둘 다 데이터 싹 밀고 새로 초기화 해두기

2) 화이트리스트 분리 확실히 해서 push 해놓기

3) https 인증서 재발급 again & 배포 과정 노션 및 벨로그 정리

### 0828 TODO 

- [x] REDIS 설치 (벨로그 글 참고)
- [x] application.yml , build.gradle 변경 (Filezilla 없으면 설치)
- [x] postgre 에 데이터 추가할 부분들 추가 
- [x] postgre utf-8 설정 , 시간 Korea 로 설정 
- [x] certbot nginx 인증서 https://jcdgods.tistory.com/476 자동 갱신 설정

**Comment by myway00** [comment]
중간에 다운 되는 이슈 있었음 (S3)
